export const CURRENCIES = [
  { code: 'CHF', name: 'Swiss Franc',        symbol: 'Fr' },
  { code: 'EUR', name: 'Euro',               symbol: '€'  },
  { code: 'USD', name: 'US Dollar',          symbol: '$'  },
  { code: 'GBP', name: 'British Pound',      symbol: '£'  },
  { code: 'JPY', name: 'Japanese Yen',       symbol: '¥'  },
  { code: 'CAD', name: 'Canadian Dollar',    symbol: 'CA$'},
  { code: 'AUD', name: 'Australian Dollar',  symbol: 'A$' },
  { code: 'NOK', name: 'Norwegian Krone',    symbol: 'kr' },
  { code: 'SEK', name: 'Swedish Krona',      symbol: 'kr' },
  { code: 'DKK', name: 'Danish Krone',       symbol: 'kr' },
  { code: 'CNY', name: 'Chinese Yuan',       symbol: '¥'  },
  { code: 'INR', name: 'Indian Rupee',       symbol: '₹'  },
  { code: 'BRL', name: 'Brazilian Real',     symbol: 'R$' },
  { code: 'MXN', name: 'Mexican Peso',       symbol: '$'  },
  { code: 'SGD', name: 'Singapore Dollar',   symbol: 'S$' },
  { code: 'HKD', name: 'Hong Kong Dollar',   symbol: 'HK$'},
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$'},
  { code: 'ZAR', name: 'South African Rand', symbol: 'R'  },
  { code: 'AED', name: 'UAE Dirham',         symbol: 'د.إ'},
  { code: 'TRY', name: 'Turkish Lira',       symbol: '₺'  },
  { code: 'PLN', name: 'Polish Złoty',       symbol: 'zł' },
  { code: 'CZK', name: 'Czech Koruna',       symbol: 'Kč' },
  { code: 'HUF', name: 'Hungarian Forint',   symbol: 'Ft' },
  { code: 'RON', name: 'Romanian Leu',       symbol: 'lei'},
  { code: 'BGN', name: 'Bulgarian Lev',      symbol: 'лв' },
  { code: 'HRK', name: 'Croatian Kuna',      symbol: 'kn' },
  { code: 'RUB', name: 'Russian Ruble',      symbol: '₽'  },
  { code: 'KRW', name: 'South Korean Won',   symbol: '₩'  },
  { code: 'THB', name: 'Thai Baht',          symbol: '฿'  },
  { code: 'IDR', name: 'Indonesian Rupiah',  symbol: 'Rp' },
  { code: 'MYR', name: 'Malaysian Ringgit',  symbol: 'RM' },
  { code: 'PHP', name: 'Philippine Peso',    symbol: '₱'  },
  { code: 'VND', name: 'Vietnamese Dong',    symbol: '₫'  },
  { code: 'ILS', name: 'Israeli Shekel',     symbol: '₪'  },
  { code: 'SAR', name: 'Saudi Riyal',        symbol: '﷼'  },
  { code: 'EGP', name: 'Egyptian Pound',     symbol: 'E£' },
  { code: 'NGN', name: 'Nigerian Naira',     symbol: '₦'  },
  { code: 'KES', name: 'Kenyan Shilling',    symbol: 'KSh'},
  { code: 'GHS', name: 'Ghanaian Cedi',      symbol: 'GH₵'},
  { code: 'CLP', name: 'Chilean Peso',       symbol: '$'  },
  { code: 'COP', name: 'Colombian Peso',     symbol: '$'  },
  { code: 'ARS', name: 'Argentine Peso',     symbol: '$'  },
  { code: 'PEN', name: 'Peruvian Sol',       symbol: 'S/' },
  { code: 'UYU', name: 'Uruguayan Peso',     symbol: '$U' },
  { code: 'MAD', name: 'Moroccan Dirham',    symbol: 'MAD'},
  { code: 'PKR', name: 'Pakistani Rupee',    symbol: '₨'  },
  { code: 'BDT', name: 'Bangladeshi Taka',   symbol: '৳'  },
  { code: 'LKR', name: 'Sri Lankan Rupee',   symbol: '₨'  },
  { code: 'NPR', name: 'Nepalese Rupee',     symbol: '₨'  },
  { code: 'TWD', name: 'Taiwan Dollar',      symbol: 'NT$'},
]

export function getCurrency(code: string) {
  return CURRENCIES.find(c => c.code === code) || { code, name: code, symbol: code }
}

export function formatAmount(amount: number, currencyCode: string): string {
  const cur = getCurrency(currencyCode)
  return `${cur.symbol} ${amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}
